# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: FirstMorphIndexer
networks:
- id: 2810
  rpc_config:
    url: https://rpc-quicknode-holesky.morphl2.io
  start_block: 0
  contracts:
  - name: DogBase
    address:
    - 0x664BB01634bE7A4855F30a7F384bA45080f34bD1
    handler: src/EventHandlers.ts
    events:
    - event: AddVaccine(uint256 indexed vacId, string indexed name, uint256 indexed tokenId, uint256 vetCentraId, uint256 date)
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: CenterVet(uint256 indexed vetCentraId, string indexed name)
    - event: DogIsFound(uint256 indexed tokenId, string addr, uint256 date)
    - event: DogIsLost(uint256 indexed tokenId, string addr, uint256 date)
    - event: MarketPlace(uint256 indexed tokenId, uint256 price)
    - event: NewDoge(uint256 indexed tokenId, string indexed name, uint256 birthday, string breed, string sex)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
rollback_on_reorg: false
